### ISSUE TITLE
file upload should accept all mimeyptes

### ISSUE THREAD

**Issue by beausmith** [votingworks/ems#80]
we cannot predict what extensions they'll use.

**Comment by beausmith** [comment]
@benadida:
> Feedback from @mcchilders  I forgot to write down: the file dialog in VxServer expects a certain file extension by default and so files on usb stick are invisible until the bottom right corner drop down is toggled.

**Comment by benadida** [comment]
this also applies to the Vx Election File file upload option, not just the election management system files.
