### ISSUE TITLE
Button to wipe card to zero state, or set as voter card.

### ISSUE THREAD

**Issue by beausmith** [votingworks/ems#92]
Once a card is programmed as an Admin or Poll Worker card, it is not possible to use it as a voter card. 

I programmed a voter card to be used as an Admin Card as I didn't have any "Admin" cards… but then realized that I could no longer use is as a voter card as there was no option to wipe the card data.

**Comment by eventualbuddha** [comment]
You can do this using module-smartcards directly, but if you think there's value in having it without a dev machine this is good to keep open.
